name: TaskGo
options:
  bundleIdPrefix: com.cruce
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

packages:
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk
    version: "11.0.0"
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    version: "2.6.0"

targets:
  TaskGo:
    type: application
    platform: macOS
    sources:
      - TaskGo
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cruce.taskgo
        PRODUCT_NAME: "TaskGo!"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        INFOPLIST_FILE: TaskGo/Info.plist
        CODE_SIGN_ENTITLEMENTS: TaskGo/TaskGo.entitlements
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "5.9"
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_HARDENED_RUNTIME: YES
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - package: firebase-ios-sdk
        product: FirebaseAuth
      - package: firebase-ios-sdk
        product: FirebaseFirestore
      - package: firebase-ios-sdk
        product: FirebaseFunctions
      - package: Sparkle
        product: Sparkle
    info:
      path: TaskGo/Info.plist
      properties:
        LSUIElement: true
        SUFeedURL: "https://crucesaunders.github.io/taskgo-app/appcast.xml"
    entitlements:
      path: TaskGo/TaskGo.entitlements
      properties:
        com.apple.security.app-sandbox: false
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-write: true
        keychain-access-groups:
          - "$(AppIdentifierPrefix)com.cruce.taskgo"
